return {
	mod_description = {
		en = "Simple customizable clock.\nBackground turns red on Tuesdays to indicate maintenance day.",
		fr = "Horloge personnalisable simple. Le fond devient rouge le mardi pour indiquer le jour de maintenance.",
		de = "Einfache anpassbare Uhr. Dienstags wird der Hintergrund rot, um den Wartungstag anzuzeigen.",
		es = "Sencillo reloj personalizable. El fondo se pone rojo los martes para indicar el día de mantenimiento.",
		ru = "Простые настраиваемые часы. По вторникам фон становится красным, что указывает на день обслуживания.",
		it = "Semplice orologio personalizzabile. Lo sfondo diventa rosso il martedì per indicare il giorno di manutenzione.",
		pl = "Prosty dostosowywalny zegar.\nTło zmienia się na czerwone we Wtorki aby przypominać o przerwie technicznej.",
		["br-pt"] = "Relógio personalizável simples. O fundo fica vermelho às terças-feiras para indicar o dia da manutenção.",
		zh = "简单的可定制时钟。背景在星期二变为红色以表示维护日。",
	},
	fontsize = {
		en = "Font size",
		fr = "Taille de police",
		de = "Schriftgröße",
		es = "Tamaño de fuente",
		ru = "Размер шрифта",
		it = "Dimensione del font",
		pl = "Rozmiar czcionki",
		["br-pt"] = "Tamanho da fonte",
		zh = "字体大小",
	},
	posx = {
		en = "Left/right position",
		fr = "Position gauche / droite",
		de = "Links / rechts Position",
		es = "Posición izquierda / derecha",
		ru = "Левая / правая позиция",
		it = "Posizione sinistra / destra",
		pl = "Pozycja lewo/prawo",
		["br-pt"] = "Posição esquerda / direita",
		zh = "左/右位置",
	},	
	posy = {
		en = "Up/down position",
		fr = "Position haut / bas",
		de = "Auf / Ab Position",
		es = "Posición arriba / abajo",
		ru = "Положение вверх / вниз",
		it = "Posizione Su / giù",
		pl = "Pozycja góra/dół",
		["br-pt"] = "Posição cima / baixo",
		zh = "上/下位置",
	},		
	colorred = {
		en = "Font color [Red]",
		fr = "Couleur de police [rouge]",
		de = "Schriftfarbe [Rot]",
		es = "Color de fuente [rojo]",
		ru = "Цвет шрифта [красный]",
		it = "Colore carattere [rosso]",
		pl = "Kolor czcionki [Czerwony]",
		["br-pt"] = "Cor da fonte [vermelho]",
		zh = "字体颜色[红色]",
	},	
	colorgreen = {
		en = "Font color [Green]",
		fr = "Couleur de police [vert]",
		de = "Schriftfarbe [Grün]",
		es = "Color de fuente [Verde]",
		ru = "Цвет шрифта [зеленый]",
		it = "Colore carattere [Verde]",
		pl = "Kolor czcionki [Zielony]",
		["br-pt"] = "Cor da fonte [Verde]",
		zh = "字体颜色[绿色]",
	},		
	colorblue = {
		en = "Font color [Blue]",
		fr = "Couleur de police [Bleu]",
		de = "Schriftfarbe [Blau]",
		es = "Color de fuente [Azul]",
		ru = "Цвет шрифта [синий]",
		it = "Colore carattere [Blu]",
		pl = "Kolor czcionki [Niebieski]",
		["br-pt"] = "Cor da fonte [Azul]",
		zh = "字体颜色[蓝色]",
	},		
	opacity = {
		en = "Font opacity",
		fr = "Opacité de la police",
		de = "Schriftdeckkraft",
		es = "Opacidad de la fuente",
		ru = "Непрозрачность шрифта",
		it = "Opacità dei caratteri",
		pl = "Przezroczystość czcionki",
		["br-pt"] = "Opacidade da fonte",
		zh = "字体不透明度",
	},	
	backgroundopacity = {
		en = "Background opacity",
		fr = "Opacité du fond",
		de = "Hintergrundopazität",
		es = "Opacidad de fondo",
		ru = "Непрозрачность фона",
		it = "Opacità di sfondo",
		pl = "Przezroczystość tła",
		["br-pt"] = "Opacidade de fundo",
		zh = "背景不透明度",
	},	
	format = {
		en = "Time format",
		fr = "Format de l'heure",
		de = "Zeitformat",
		es = "Formato de tiempo",
		ru = "Формат времени",
		it = "Formato orario",
		pl = "Format czasu",
		["br-pt"] = "Formato da hora",
		zh = "时间格式",
	},	
	["24h"] = {
		en = "24 hours",
		fr = "24 heures",
		de = "24 Stunden",
		es = "24 horas",
		ru = "24 часа",
		it = "24 ore",
		pl = "24 godzinny",
		["br-pt"] = "24 horas",
		zh = "24小时",
	},	
	["12h"] = {
		en = "12 hours",
		fr = "12 heures",
		de = "12 Stunden",
		es = "12 horas",
		ru = "12 часа",
		it = "12 ore",
		pl = "12 godzinny",
		["br-pt"] = "12 horas",
		zh = "12小时",
	},		
}